title       = "ols"
baseURL     = "https://ols-cli.tamnd.com/"
description = "A command line for ols."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ols-cli"
